apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jlc-mysql-persistent-volume
  labels:
    mypvc: jlc-mysql-persistent-volume
spec:
  storageClassName: jlc-mysql-storage-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

