apiVersion: v1
kind: Service
metadata:
  name: jlc-mysql-service
  labels:
    app: jlc-mysql-service
    tier: database    
spec:
  type: ClusterIP
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: jlc-mysql
    tier: database