pipeline {
  agent any
    tools {
      maven 'mymaven3'
      jdk 'myjdk8'
    }

    stages {      
        stage('1. Build the Bookstore Application') {
            steps { 
                    sh 'pwd'      
                    sh 'mvn  clean install package'
            }
        }
        
        stage('2. Copy the Application War to myjlc-docker') {
           steps { 
                   sh 'pwd'
                   sh 'cp -r target/*.war myjlc-docker'
           }
        }
         
        stage('3. Build the docker image') {
           steps {
               script {         
                 def customImage = docker.build('dandesclasses/myjlc-bookstore', "./myjlc-docker")
                 docker.withRegistry('https://registry-1.docker.io/v2/', 'mydockerhub') {
                 customImage.push("5.0")
                 }                     
           }
        }
	  }
    }
}

